### PR TITLE
Add OpenShift SSPTOOL template

### PR DESCRIPTION
**Pull request by redhatrises**
Adds an initial OCP template to be expanded upon as needed.

### CODE REVIEW

**Comment by shawndwells** [comment]
Hey @jenglish! @redhatrises and I work together at Red Hat. We've began using the ssptool a good bit and would like to upstream the openshift template needed to make ssptool work natively on OpenShift v3. 

Happy to carry the patches elsewhere, but the Red Hat way is to try and upstream everything first. This way we can collaborate and ensure the template can be kept in sync with your work.

**Comment by jenglish** [comment]
OK... what exactly does the template file do? (Sorry, I'm not yet familiar with OpenShift).
Does it need to be in the top-level directory?

**Comment by shawndwells** [comment]
On 3/19/18 1:08 PM, Joe English wrote:
> OK... what exactly does the template file do? (Sorry, I'm not yet
> familiar with OpenShift).
Think of it like a Dockerfile for OpenShift. Template file that you
import, and OpenShift executes to create a running instance of the
application. Works on openshift.com and on-prem deployments.
> Does it need to be in the top-level directory?
No. We could create a deployment_templates directory (or some other name).

**Comment by redhatrises** [comment]
>>  Does it need to be in the top-level directory?
>
> No. We could create a deployment_templates directory (or some other name).

It doesn't necessarily need to be in the top level directory. Although for simplicity, OpenShift templates seem to either be put in the top-level directory or a separate git repository.

**Pull request closed without merging**
